steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    # Step 1: Build the Java app

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld-backend', '.']
    # Step 2: Build Docker image

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/helloworld-backend']
    # Step 3: Push image to GCR

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'helloworld-backend',
      '--image', 'gcr.io/$PROJECT_ID/helloworld-backend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
    # Step 4: Deploy image to Cloud Run

images:
  - 'gcr.io/$PROJECT_ID/helloworld-backend'

options:
  logging: CLOUD_LOGGING_ONLY
  \